[project]
name = "graphs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arcade>=3.3.2",
    "matplotlib>=3.10.3",
    "networkx>=3.5",
]
